// Contains the mappings from the Octopart component and spec IDs to the corresponding display values and shortnames.

// https://octopart.com/api/v4/values#categories
export const categoryIds: { [key: string]: string } = {
  "Passive Components": "4165",
  "Capacitors": "4166",
  "Aluminum Electrolytic Capacitors": "6331",
  "Capacitor Arrays": "4169",
  "Capacitor Kits": "4172",
  "Ceramic Capacitors": "6332",
  "Film Capacitors": "6333",
  "Mica Capacitors": "6334",
  "Polymer Capacitors": "6335",
  "Tantalum Capacitors": "6336",
  "Trimmer / Variable Capacitors": "4168",
  "Inductors": "4190",
  "Fixed Inductors": "4193",
  "Inductor Kits": "6259",
  "Variable Inductors": "4191",
  "Transformers": "4197",
};

export const categoryNames: { [key: string]: string } = {
  "4165": "Passive Components",
  "4166": "Capacitors",
  "6331": "Aluminum Electrolytic Capacitors",
  "4169": "Capacitor Arrays",
  "4172": "Capacitor Kits",
  "6332": "Ceramic Capacitors",
  "6333": "Film Capacitors",
  "6334": "Mica Capacitors",
  "6335": "Polymer Capacitors",
  "6336": "Tantalum Capacitors",
  "4168": "Trimmer / Variable Capacitors",
  "4190": "Inductors",
  "4193": "Fixed Inductors",
  "6259": "Inductor Kits",
  "4191": "Variable Inductors",
  "4197": "Transformers",
};

// https://octopart.com/api/v4/values#attributes
export const attributeShortnames: { [key: string]: string } = {
  Capacitance: "capacitance",
  "Case/Package": "case_package",
  "Contact Plating": "contactplating",
  Diameter: "diameter",
  "Dielectric Material": "dielectricmaterial",
  "Dissipation Factor": "dissipationfactor",
  "ESR (Equivalent Series Resistance)": "esr_equivalentseriesresistance_",
  Features: "features",
  Height: "height",
  "Height - Seated (Max)": "height_seated_max_",
  "Hole Diameter": "holediameter",
  Impedance: "impedance",
  "Lead Diameter": "leaddiameter",
  "Lead Free": "leadfree",
  "Lead Length": "leadlength",
  "Lead Pitch": "leadpitch",
  "Lead/Base Style": "lead_basestyle",
  "Leakage Current": "leakagecurrent",
  Length: "length",
  "Life (Hours)": "life_hours_",
  "Lifecycle Status": "lifecyclestatus",
  Material: "material",
  "Max Operating Temperature": "maxoperatingtemperature",
  "Min Operating Temperature": "minoperatingtemperature",
  Mount: "mount",
  "Number of Pins": "numberofpins",
  Packaging: "packaging",
  Polarity: "polarity",
  "REACH SVHC": "reachsvhc",
  "Radiation Hardening": "radiationhardening",
  Resistance: "resistance",
  "Ripple Current": "ripplecurrent",
  "Ripple Current (AC)": "ripplecurrent_ac_",
  RoHS: "rohs",
  "Schedule B": "scheduleB",
  Termination: "termination",
  "Test Frequency": "testfrequency",
  Tolerance: "tolerance",
  Voltage: "voltage",
  "Voltage Rating": "voltagerating",
  "Voltage Rating (AC)": "voltagerating_ac_",
  "Voltage Rating (DC)": "voltagerating_dc_",
  Weight: "weight",
  Width: "width",
  "Case Code (Imperial)": "casecode_imperial_",
  "Case Code (Metric)": "casecode_metric_",
  Composition: "composition",
  Depth: "depth",
  Dielectric: "dielectric",
  "Manufacturer Lifecycle Status": "manufacturerlifecyclestatus",
  Ratings: "ratings",
  "Temperature Coefficient": "temperaturecoefficient",
  Thickness: "thickness",
  "Military Standard": "militarystandard",
  "Core Material": "corematerial",
  "Current Rating": "currentrating",
  "DC Resistance (DCR)": "dcresistance_dcr_",
  "Failure Rate": "failurerate",
  Frequency: "frequency",
  "Frequency Stability": "frequencystability",
  Inductance: "inductance",
  "Max DC Current": "maxdccurrent",
  "Max Junction Temperature (Tj)": "maxjunctiontemperature",
  "Max Power Dissipation": "maxpowerdissipation",
  "Max Supply Voltage": "maxsupplyvoltage",
  "Min Supply Voltage": "minsupplyvoltage",
  "Nominal Supply Current": "nominalsupplycurrent",
  "Nominal Supply Voltage (DC)": "nominalsupplyvoltage_dc_",
  "Number of Terminations": "numberofterminations",
  "Operating Supply Voltage": "operatingsupplyvoltage",
  "Power Rating": "powerrating",
  "Self Resonant Frequency": "selfresonantfrequency",
  Shielding: "shielding",
  "Insulation Resistance": "insulationresistance",
  Type: "type",
  Color: "color",
  "Q Factor": "qfactor",
  Current: "current",
  "DC Current": "dccurrent",
  "Inductance Tolerance": "inductancetolerance",
  "Max Length": "maxlength",
  "Max Width": "maxwidth",
  "Min Length": "minlength",
  "Min Width": "minwidth",
  "RMS Current (Irms)": "rmscurrent_irms_",
  "Saturation Current": "saturationcurrent",
  "Series Resistance": "seriesresistance",
  "Halogen Free": "halogenfree",
  "Max Saturation Current": "maxsatcurrent",
  "Max Temperature Rise Current": "maxtemprisecurrent",
  "Connector Type": "connectortype",
};

// https://octopart.com/api/v4/values#attributes
export const attributeIds: { [key: string]: string } = {
  Capacitance: "548",
  "Case/Package": "842",
  "Contact Plating": "384",
  Diameter: "418",
  "Dielectric Material": "834",
  "Dissipation Factor": "389",
  "ESR (Equivalent Series Resistance)": "308",
  Features: "587",
  Height: "468",
  "Height - Seated (Max)": "386",
  "Hole Diameter": "539",
  Impedance: "495",
  "Lead Diameter": "473",
  "Lead Free": "724",
  "Lead Length": "545",
  "Lead Pitch": "285",
  "Lead/Base Style": "852",
  "Leakage Current": "434",
  Length: "755",
  "Life (Hours)": "839",
  "Lifecycle Status": "910",
  Material: "354",
  "Max Operating Temperature": "849",
  "Min Operating Temperature": "456",
  Mount: "773",
  "Number of Pins": "329",
  Packaging: "412",
  Polarity: "597",
  "REACH SVHC": "683",
  "Radiation Hardening": "634",
  Resistance: "440",
  "Ripple Current": "521",
  "Ripple Current (AC)": "770",
  RoHS: "610",
  "Schedule B": "973",
  Termination: "717",
  "Test Frequency": "684",
  Tolerance: "342",
  Voltage: "324",
  "Voltage Rating": "457",
  "Voltage Rating (AC)": "340",
  "Voltage Rating (DC)": "323",
  Weight: "547",
  Width: "576",
  "Case Code (Imperial)": "572",
  "Case Code (Metric)": "769",
  Composition: "371",
  Depth: "291",
  Dielectric: "357",
  "Manufacturer Lifecycle Status": "942",
  Ratings: "559",
  "Temperature Coefficient": "321",
  Thickness: "286",
  "Military Standard": "478",
  "Core Material": "392",
  "Current Rating": "638",
  "DC Resistance (DCR)": "201",
  "Failure Rate": "233",
  Frequency: "505",
  "Frequency Stability": "223",
  Inductance: "375",
  "Max DC Current": "359",
  "Max Junction Temperature (Tj)": "905",
  "Max Power Dissipation": "663",
  "Max Supply Voltage": "588",
  "Min Supply Voltage": "339",
  "Nominal Supply Current": "422",
  "Nominal Supply Voltage (DC)": "670",
  "Number of Terminations": "784",
  "Operating Supply Voltage": "637",
  "Power Rating": "257",
  "Self Resonant Frequency": "230",
  Shielding: "831",
  "Insulation Resistance": "563",
  Type: "206",
  Color: "743",
  "Q Factor": "577",
  Current: "299",
  "DC Current": "282",
  "Inductance Tolerance": "682",
  "Max Length": "939",
  "Max Width": "933",
  "Min Length": "940",
  "Min Width": "934",
  "RMS Current (Irms)": "465",
  "Saturation Current": "581",
  "Series Resistance": "224",
  "Halogen Free": "687",
  "Max Saturation Current": "928",
  "Max Temperature Rise Current": "931",
  "Connector Type": "250",
};

export const attributeNames: { [key: string]: string } = {
  "548": "Capacitance",
  "842": "Case/Package",
  "384": "Contact Plating",
  "418": "Diameter",
  "834": "Dielectric Material",
  "389": "Dissipation Factor",
  "308": "ESR (Equivalent Series Resistance)",
  "587": "Features",
  "468": "Height",
  "386": "Height - Seated (Max)",
  "539": "Hole Diameter",
  "495": "Impedance",
  "473": "Lead Diameter",
  "724": "Lead Free",
  "545": "Lead Length",
  "285": "Lead Pitch",
  "852": "Lead/Base Style",
  "434": "Leakage Current",
  "755": "Length",
  "839": "Life (Hours)",
  "910": "Lifecycle Status",
  "354": "Material",
  "849": "Max Operating Temperature",
  "456": "Min Operating Temperature",
  "773": "Mount",
  "329": "Number of Pins",
  "412": "Packaging",
  "597": "Polarity",
  "683": "REACH SVHC",
  "634": "Radiation Hardening",
  "440": "Resistance",
  "521": "Ripple Current",
  "770": "Ripple Current (AC)",
  "610": "RoHS",
  "973": "Schedule B",
  "717": "Termination",
  "684": "Test Frequency",
  "342": "Tolerance",
  "324": "Voltage",
  "457": "Voltage Rating",
  "340": "Voltage Rating (AC)",
  "323": "Voltage Rating (DC)",
  "547": "Weight",
  "576": "Width",
  "572": "Case Code (Imperial)",
  "769": "Case Code (Metric)",
  "371": "Composition",
  "291": "Depth",
  "357": "Dielectric",
  "942": "Manufacturer Lifecycle Status",
  "559": "Ratings",
  "321": "Temperature Coefficient",
  "286": "Thickness",
  "478": "Military Standard",
  "392": "Core Material",
  "638": "Current Rating",
  "201": "DC Resistance (DCR)",
  "233": "Failure Rate",
  "505": "Frequency",
  "223": "Frequency Stability",
  "375": "Inductance",
  "359": "Max DC Current",
  "905": "Max Junction Temperature (Tj)",
  "663": "Max Power Dissipation",
  "588": "Max Supply Voltage",
  "339": "Min Supply Voltage",
  "422": "Nominal Supply Current",
  "670": "Nominal Supply Voltage (DC)",
  "784": "Number of Terminations",
  "637": "Operating Supply Voltage",
  "257": "Power Rating",
  "230": "Self Resonant Frequency",
  "831": "Shielding",
  "563": "Insulation Resistance",
  "206": "Type",
  "743": "Color",
  "577": "Q Factor",
  "299": "Current",
  "282": "DC Current",
  "682": "Inductance Tolerance",
  "939": "Max Length",
  "933": "Max Width",
  "940": "Min Length",
  "934": "Min Width",
  "465": "RMS Current (Irms)",
  "581": "Saturation Current",
  "224": "Series Resistance",
  "687": "Halogen Free",
  "928": "Max Saturation Current",
  "931": "Max Temperature Rise Current",
  "250": "Connector Type",
};
